fuse: detect fusepy module
When importing 'fuse', we might get either the libfuse or
the fusepy module, the latter doesn't have __version__ so
we just print

  error: fuse module is too old for fuse.__version__

but that's misleading. Detect if we have fuse.FUSE and in
that case instead print

  error: you have the "fusepy" module rather than the "libfuse" one
         please install https://github.com/libfuse/python-fuse

Signed-off-by: Johannes Berg <johannes@sipsolutions.net>